name: Track Deployments

on:
  deployment:

jobs:
  track-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Log Deployment
        run: |
          echo "Deployment at: $(date)"
          echo "Environment: ${{ github.event.deployment.environment }}"


          